// ── Input ──────────────────────────────────────────────────────────────────

export interface InputState {
  left: boolean;
  right: boolean;
  jumpPressed: boolean;    // true only on the frame the jump key was pressed
  jumpHeld: boolean;       // true while jump key is held (for variable jump height later)
  pausePressed: boolean;   // true only on the frame pause was triggered (keyboard or button)
  restartPressed: boolean; // true only on the frame restart was triggered (R key or button)
}

// ── Game State ──────────────────────────────────────────────────────────────

export type GameState = "playing" | "paused" | "gameOver" | "towerComplete";
export type DeathReason = "fall_damage_landing";

// ── Score ───────────────────────────────────────────────────────────────────

export interface ScoreSnapshot {
  currentHeightMeters: number;
  bestHeightMeters: number;
  score: number;
}

// ── Player ─────────────────────────────────────────────────────────────────

export type FacingDirection = "left" | "right";

export interface PlayerConfig {
  moveSpeed: number;
  jumpVelocity: number;
  // Reserved for future mechanics:
  // coyoteTime: number;
  // jumpBufferTime: number;
}

// ── Platform ───────────────────────────────────────────────────────────────

export type PlatformType = "normal" | "slippery" | "breakable" | "moving" | "goal";

// Pre-computed bounds + speed for a moving platform; generated by PlatformManager.
export interface MovingPlatformConfig {
  speedPxPerSecond: number;
  minX: number;
  maxX: number;
}

export interface PlatformConfig {
  x: number;
  y: number;
  width: number;
  type: PlatformType;
  moving?: MovingPlatformConfig;
}

// Per-frame outcome of PlatformManager.update(), surfaced so GameScene can
// fire platform-break SFX/FX without reaching into platform internals.
export interface PlatformManagerUpdateResult {
  // Number of platforms that finished breaking (transitioned to broken) this frame.
  brokenPlatformsCount: number;
  // World positions of those platforms, so FX can spawn ice shards at each.
  brokenPlatformPositions: Array<{ x: number; y: number }>;
}

// ── Tower / Phase ──────────────────────────────────────────────────────────

export interface TowerPhaseConfig {
  id: string;
  name: string;
  theme: string;
  height: number;
  gravity: number;
  playerMoveSpeed: number;
  playerJumpVelocity: number;
}

// ── Hazard events ────────────────────────────────────────────────────────────

export type HazardEventType =
  | "side_projectile_warning"
  | "side_projectile_fire"
  | "snow_start"
  | "snow_end";

export type HazardSide = "left" | "right";

// One scheduled hazard moment, emitted by HazardEventScheduler.update().
export interface HazardEventPayload {
  type: HazardEventType;
  side?: HazardSide;     // present only for projectile events
  heightMeters: number;  // run height when the event fired
  time: number;          // scene time (ms) when the event fired
}

// Read-only view of the scheduler's internal state (debug / future HUD).
export interface HazardSchedulerSnapshot {
  isProjectileHazardEnabled: boolean;
  isSnowActive: boolean;
  snowEventsUsed: number;
  nextProjectileFireInMs: number;
  nextSnowEventInMs: number;
}

// ── Side projectile (Step 13) ───────────────────────────────────────────────

export interface ProjectileConfig {
  x: number;
  y: number;
  radius: number;
  velocityX: number;
  velocityY: number;
  // Net downward gravity (px/s²) the projectile should feel.
  gravityY: number;
  bounce: number;
  side: HazardSide;
}

// Raw data delivered to GameScene when a projectile overlaps the player, so the
// knockback can be computed against config without the manager knowing physics.
export interface ProjectileHitPayload {
  projectileVelocityX: number;
  projectileVelocityY: number;
  projectileX: number;
  projectileY: number;
  playerX: number;
  playerY: number;
  side: HazardSide;
}

// ── Hailstones (Step 14.3, mixed into Snow Time) ─────────────────────────────

export interface HailstoneConfig {
  x: number;
  y: number;
  radius: number;
  velocityX: number;
  velocityY: number;
  gravityY: number; // net downward gravity (px/s²)
  bounce: number;
}

export interface HailstoneHitPayload {
  hailstoneVelocityX: number;
  hailstoneVelocityY: number;
  hailstoneX: number;
  hailstoneY: number;
  playerX: number;
  playerY: number;
}

// ── Camera ─────────────────────────────────────────────────────────────────

export interface CameraConfig {
  // How far above the player the camera top boundary sits.
  // Future: camera only scrolls up (not back down easily).
  topMargin: number;
}

// ── Platform Generation ────────────────────────────────────────────────────

export interface PlatformGenerationConfig {
  /** How many platforms to create during initial scene setup. */
  initialPlatformCount: number;
  /** Generate platforms this many px above the current player Y. */
  generateAheadDistance: number;
  /** Destroy platforms this many px below the camera's bottom edge. */
  cleanupBelowDistance: number;
  minVerticalGap: number;
  maxVerticalGap: number;
  minPlatformWidth: number;
  maxPlatformWidth: number;
  /** Minimum px margin from world edges for platform placement. */
  safeHorizontalPadding: number;
  /** Max candidate attempts before using a fallback position. */
  maxGenerationAttempts: number;
  /** Scales theoretical max horizontal reach for reachability checks (0–1). */
  airControlMultiplier: number;
}
